name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # o branch che usi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # versione Node.js

      - name: Install dependencies
        run: npm install

      - name: Build static site
        run: npm run build  index.html # il tuo script per generare sito statico

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # cambia se la cartella build è diversa
